//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDiagram")]

namespace UPM_IPS.JRPPCLMCFProyectoIPS
{
	/// <summary>
	/// DomainClass JRPPCLMCFProyectoIPSDiagram
	/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDiagram.DisplayName", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDiagram.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("ee20020f-f5a7-4283-8a1c-000653ff7475")]
	public partial class JRPPCLMCFProyectoIPSDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Compartment support
		/// <summary>
		/// Whether compartment items change events are subscribed to.
		/// </summary>
		private bool subscribedCompartmentItemsEvents;
		
		/// <summary>
		/// Subscribe to events fired when compartment items changes.
		/// </summary>
		public void SubscribeCompartmentItemsEvents()
		{
			if (!subscribedCompartmentItemsEvents && this.Store != null)
			{
				subscribedCompartmentItemsEvents = true;
				this.Store.EventManagerDirectory.ElementAdded.Add(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Add(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Add(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
			}
		}
		
		/// <summary>
		/// Unsubscribe to events fired when compartment items changes.
		/// </summary>
		public void UnsubscribeCompartmentItemsEvents()
		{
			if (subscribedCompartmentItemsEvents)
			{
				this.Store.EventManagerDirectory.ElementAdded.Remove(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Remove(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Remove(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
				subscribedCompartmentItemsEvents = false;
			}
		}
		
		#region Event handlers
		/// <summary>
		/// Event for element added.
		/// </summary>
		private void CompartmentItemAdded(object sender, DslModeling::ElementAddedEventArgs e)
		{
			// If in Undo, Redo or Rollback the compartment item rules are not run so we must refresh the compartment list at this point if required
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemAddRule.ElementAdded(e, repaintOnly);
		}
		/// <summary>
		/// Event for element deleted.
		/// </summary>
		private void CompartmentItemDeleted(object sender, DslModeling::ElementDeletedEventArgs e)
		{
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemDeleteRule.ElementDeleted(e, repaintOnly);
		}
		/// <summary>
		/// Event for element property changed.
		/// </summary>
		private void CompartmentItemPropertyChanged(object sender, DslModeling::ElementPropertyChangedEventArgs e)
		{
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemChangeRule.ElementPropertyChanged(e, repaintOnly);
		}
		/// <summary>
		/// Event for role-player changed.
		/// </summary>
		private void CompartmentItemRolePlayerChanged(object sender, DslModeling::RolePlayerChangedEventArgs e)
		{
			bool repaintOnly = !e.ElementLink.Store.InUndoRedoOrRollback;
			CompartmentItemRolePlayerChangeRule.RolePlayerChanged(e, repaintOnly);
		}
		/// <summary>
		/// Event for role-player order changed.
		/// </summary>
		private void CompartmentItemRolePlayerOrderChanged(object sender, DslModeling::RolePlayerOrderChangedEventArgs e)
		{
			bool repaintOnly = !e.Link.Store.InUndoRedoOrRollback;
			CompartmentItemRolePlayerPositionChangeRule.RolePlayerPositionChanged(e, repaintOnly);
		}
		#endregion
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecida)
			{
				global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape newShape = new global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JRPPCLMCFProyectoIPS.Clase)
			{
				global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora newShape = new global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloClase)
			{
				global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloClaseShape newShape = new global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloClaseShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloAtributo)
			{
				global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloAtributoShape newShape = new global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloAtributoShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloOperacion)
			{
				global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloOperacionShape newShape = new global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloOperacionShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JRPPCLMCFProyectoIPS.Parametro)
			{
				global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaParametro newShape = new global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaParametro(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumerador)
			{
				global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaEnumerador newShape = new global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaEnumerador(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JRPPCLMCFProyectoIPS.AtributoIdentificador)
			{
				global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaAtributoIdentificador newShape = new global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaAtributoIdentificador(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase)
			{
				global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaClase_Clase newShape = new global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaClase_Clase(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseComponeClases)
			{
				global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaRComposicion newShape = new global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaRComposicion(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferenciaClase)
			{
				global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaReferenciada newShape = new global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaReferenciada(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClasePadreHasClaseHija)
			{
				global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaHerencia newShape = new global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaHerencia(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora.DecoratorsInitialized += ClaseMetaforaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape.DecoratorsInitialized += ClaseEnriquecidaShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloClaseShape.DecoratorsInitialized += EstiloClaseShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloAtributoShape.DecoratorsInitialized += EstiloAtributoShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloOperacionShape.DecoratorsInitialized += EstiloOperacionShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaParametro.DecoratorsInitialized += MetaforaParametroDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaEnumerador.DecoratorsInitialized += MetaforaEnumeradorDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaAtributoIdentificador.DecoratorsInitialized += MetaforaAtributoIdentificadorDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaClase_Clase.DecoratorsInitialized += MetaforaClase_ClaseDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaRComposicion.DecoratorsInitialized += MetaforaRComposicionDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaReferenciada.DecoratorsInitialized += MetaforaReferenciadaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaHerencia.DecoratorsInitialized += MetaforaHerenciaDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ClaseMetafora.
		/// </summary>
		internal static partial class ClaseMetaforaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ClaseMetafora.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.Clase.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ClaseEnriquecidaShape.
		/// </summary>
		internal static partial class ClaseEnriquecidaShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ClaseEnriquecidaShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.Clase.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for EstiloClaseShape.
		/// </summary>
		internal static partial class EstiloClaseShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for EstiloClaseShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloClase.alineacionDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "alineacionCalculadaDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloClase.colorFondoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "colorFondoCalculadoDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloClase.colorLetraDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "colorLetraCalculadoDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloClase.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloClase.tipoLetraDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "tipoLetraCalculadoDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for EstiloAtributoShape.
		/// </summary>
		internal static partial class EstiloAtributoShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for EstiloAtributoShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloAtributo.colorLetraCalculadoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "colorDeLetraCalculadoDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloAtributo.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloAtributo.tipoLetraCalculadoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "tipoLetraCalculadoDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for EstiloOperacionShape.
		/// </summary>
		internal static partial class EstiloOperacionShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for EstiloOperacionShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloOperacion.colorLetraDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "colorLetraCalculadoDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloOperacion.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloOperacion.tipoLetraDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "tipoLetraCalculadoDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaParametro.
		/// </summary>
		internal static partial class MetaforaParametroDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaParametro.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.Parametro.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.Parametro.tipoParametroCalculadoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "tipoParametroDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaEnumerador.
		/// </summary>
		internal static partial class MetaforaEnumeradorDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaEnumerador.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumerador.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaAtributoIdentificador.
		/// </summary>
		internal static partial class MetaforaAtributoIdentificadorDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaAtributoIdentificador.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.AtributoIdentificador.tipoDatoCalculadoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "tipoDatoCalculadaDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaClase_Clase.
		/// </summary>
		internal static partial class MetaforaClase_ClaseDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaClase_Clase.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase.cardinalidadDCalculadaDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidadDDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase.cardinalidadOCalculadaDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidadODec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase.nombreDDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase.nombreODomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreODec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase.nombreRDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreRDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaRComposicion.
		/// </summary>
		internal static partial class MetaforaRComposicionDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaRComposicion.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseComponeClases.cardinalidadDDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidadDDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseComponeClases.cardinalidadODomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidadODec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseComponeClases.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaReferenciada.
		/// </summary>
		internal static partial class MetaforaReferenciadaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaReferenciada.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferenciaClase.cardinalidadDDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidadDDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferenciaClase.cardinalidadODomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidadODec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferenciaClase.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaHerencia.
		/// </summary>
		internal static partial class MetaforaHerenciaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaHerencia.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClasePadreHasClaseHija.tipoHerenciaDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "tipoHerenciaDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::UPM_IPS.JRPPCLMCFProyectoIPS.AsociacionConnectAction asociacionConnectAction;
		private global::UPM_IPS.JRPPCLMCFProyectoIPS.HerenciaConnectAction herenciaConnectAction;
		private global::UPM_IPS.JRPPCLMCFProyectoIPS.ComposicionConnectAction composicionConnectAction;
		private global::UPM_IPS.JRPPCLMCFProyectoIPS.ReferencialConnectAction referencialConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSToolboxHelper.AsociacionFilterString))
				{
					if (this.asociacionConnectAction == null)
					{
						this.asociacionConnectAction = new global::UPM_IPS.JRPPCLMCFProyectoIPS.AsociacionConnectAction(this);
						this.asociacionConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.asociacionConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSToolboxHelper.HerenciaFilterString))
				{
					if (this.herenciaConnectAction == null)
					{
						this.herenciaConnectAction = new global::UPM_IPS.JRPPCLMCFProyectoIPS.HerenciaConnectAction(this);
						this.herenciaConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.herenciaConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSToolboxHelper.ComposicionFilterString))
				{
					if (this.composicionConnectAction == null)
					{
						this.composicionConnectAction = new global::UPM_IPS.JRPPCLMCFProyectoIPS.ComposicionConnectAction(this);
						this.composicionConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.composicionConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSToolboxHelper.ReferencialFilterString))
				{
					if (this.referencialConnectAction == null)
					{
						this.referencialConnectAction = new global::UPM_IPS.JRPPCLMCFProyectoIPS.ReferencialConnectAction(this);
						this.referencialConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.referencialConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.asociacionConnectAction != null)
					{
						this.asociacionConnectAction.Dispose();
						this.asociacionConnectAction = null;
					}
					if(this.herenciaConnectAction != null)
					{
						this.herenciaConnectAction.Dispose();
						this.herenciaConnectAction = null;
					}
					if(this.composicionConnectAction != null)
					{
						this.composicionConnectAction.Dispose();
						this.composicionConnectAction = null;
					}
					if(this.referencialConnectAction != null)
					{
						this.referencialConnectAction.Dispose();
						this.referencialConnectAction = null;
					}
					this.UnsubscribeCompartmentItemsEvents();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// JRPPCLMCFProyectoIPSDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xee20020f, 0xf5a7, 0x4283, 0x8a, 0x1c, 0x00, 0x06, 0x53, 0xff, 0x74, 0x75);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public JRPPCLMCFProyectoIPSDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public JRPPCLMCFProyectoIPSDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace UPM_IPS.JRPPCLMCFProyectoIPS
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecida), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.Clase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloClase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloAtributo), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloOperacion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.Parametro), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumerador), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.AtributoIdentificador), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseComponeClases), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferenciaClase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClasePadreHasClaseHija), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecida)
				{
					parentElement = GetParentForClaseEnriquecida((global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecida)childElement);
				} else
				if(childElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.Clase)
				{
					parentElement = GetParentForClase((global::UPM_IPS.JRPPCLMCFProyectoIPS.Clase)childElement);
				} else
				if(childElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloClase)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForEstiloClase(EstiloClase childElement)
					// {
					// }
					// must be implemented in a partial class of UPM_IPS.JRPPCLMCFProyectoIPS.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForEstiloClase((global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloClase)childElement);
				} else
				if(childElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloAtributo)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForEstiloAtributo(EstiloAtributo childElement)
					// {
					// }
					// must be implemented in a partial class of UPM_IPS.JRPPCLMCFProyectoIPS.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForEstiloAtributo((global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloAtributo)childElement);
				} else
				if(childElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloOperacion)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForEstiloOperacion(EstiloOperacion childElement)
					// {
					// }
					// must be implemented in a partial class of UPM_IPS.JRPPCLMCFProyectoIPS.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForEstiloOperacion((global::UPM_IPS.JRPPCLMCFProyectoIPS.EstiloOperacion)childElement);
				} else
				if(childElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.Parametro)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForParametro(Parametro childElement)
					// {
					// }
					// must be implemented in a partial class of UPM_IPS.JRPPCLMCFProyectoIPS.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForParametro((global::UPM_IPS.JRPPCLMCFProyectoIPS.Parametro)childElement);
				} else
				if(childElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumerador)
				{
					parentElement = GetParentForClaseEnumerador((global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumerador)childElement);
				} else
				if(childElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.AtributoIdentificador)
				{
					parentElement = GetParentForAtributoIdentificador((global::UPM_IPS.JRPPCLMCFProyectoIPS.AtributoIdentificador)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::UPM_IPS.JRPPCLMCFProyectoIPS.TapizClassWeb GetParentForClase( global::UPM_IPS.JRPPCLMCFProyectoIPS.Clase root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JRPPCLMCFProyectoIPS.TapizClassWeb result = root.TapizClassWeb;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JRPPCLMCFProyectoIPS.TapizClassWeb GetParentForClaseEnriquecida( global::UPM_IPS.JRPPCLMCFProyectoIPS.Clase root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JRPPCLMCFProyectoIPS.TapizClassWeb result = root.TapizClassWeb;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JRPPCLMCFProyectoIPS.TapizClassWeb GetParentForClaseEnumerador( global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumerador root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JRPPCLMCFProyectoIPS.TapizClassWeb result = root.TapizClassWeb;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JRPPCLMCFProyectoIPS.TapizClassWeb GetParentForAtributoIdentificador( global::UPM_IPS.JRPPCLMCFProyectoIPS.AtributoIdentificador root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JRPPCLMCFProyectoIPS.Clase root2 = root.Clase;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.JRPPCLMCFProyectoIPS.TapizClassWeb result = root2.TapizClassWeb;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
		/// <summary>
		/// Rule to update compartments when an item is added to the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumeradorHasEnumeradors), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemAddRule : DslModeling::AddRule
		{
			/// <summary>
			/// Called when an element is added. 
			/// </summary>
			/// <param name="e"></param>
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				ElementAdded(e, false);
			}
	
			internal static void ElementAdded(DslModeling::ElementAddedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if (e.ModelElement.IsDeleted)
					return;
				if(e.ModelElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo)
				{
					global::System.Collections.IEnumerable elements = GetClaseForClaseMetaforaAtributoFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo)e.ModelElement);
					UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora), "Atributo", repaintOnly);
				}
				if(e.ModelElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion)
				{
					global::System.Collections.IEnumerable elements = GetClaseForClaseMetaforaOpereacionFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion)e.ModelElement);
					UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora), "Opereacion", repaintOnly);
				}
				if(e.ModelElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo)
				{
					global::System.Collections.IEnumerable elements = GetClaseEnriquecidaForClaseEnriquecidaShapeatributoDecFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo)e.ModelElement);
					UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape), "atributoDec", repaintOnly);
				}
				if(e.ModelElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion)
				{
					global::System.Collections.IEnumerable elements = GetClaseEnriquecidaForClaseEnriquecidaShapeoperacionDecFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion)e.ModelElement);
					UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape), "operacionDec", repaintOnly);
				}
				if(e.ModelElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumeradorHasEnumeradors)
				{
					global::System.Collections.IEnumerable elements = GetClaseEnumeradorForMetaforaEnumeradorenumeradorDecFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumeradorHasEnumeradors)e.ModelElement);
					UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaEnumerador), "enumeradorDec", repaintOnly);
				}
			}
			
			#region static DomainPath traversal methods to get the list of compartments to update
			internal static global::System.Collections.ICollection GetClaseForClaseMetaforaAtributoFromLastLink(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo root)
			{
				// Segment 0
				global::UPM_IPS.JRPPCLMCFProyectoIPS.Clase result = root.Clase;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetClaseForClaseMetaforaAtributo(global::UPM_IPS.JRPPCLMCFProyectoIPS.Atributo root)
			{
				// Segments 1 and 0
				global::UPM_IPS.JRPPCLMCFProyectoIPS.Clase result = root.Clase;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetClaseForClaseMetaforaOpereacionFromLastLink(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion root)
			{
				// Segment 0
				global::UPM_IPS.JRPPCLMCFProyectoIPS.Clase result = root.Clase;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetClaseForClaseMetaforaOpereacion(global::UPM_IPS.JRPPCLMCFProyectoIPS.Operacion root)
			{
				// Segments 1 and 0
				global::UPM_IPS.JRPPCLMCFProyectoIPS.Clase result = root.Clase;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetClaseEnriquecidaForClaseEnriquecidaShapeatributoDecFromLastLink(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo root)
			{
				// Segment 0
				global::UPM_IPS.JRPPCLMCFProyectoIPS.Clase result = root.Clase;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetClaseEnriquecidaForClaseEnriquecidaShapeatributoDec(global::UPM_IPS.JRPPCLMCFProyectoIPS.Atributo root)
			{
				// Segments 1 and 0
				global::UPM_IPS.JRPPCLMCFProyectoIPS.Clase result = root.Clase;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetClaseEnriquecidaForClaseEnriquecidaShapeoperacionDecFromLastLink(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion root)
			{
				// Segment 0
				global::UPM_IPS.JRPPCLMCFProyectoIPS.Clase result = root.Clase;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetClaseEnriquecidaForClaseEnriquecidaShapeoperacionDec(global::UPM_IPS.JRPPCLMCFProyectoIPS.Operacion root)
			{
				// Segments 1 and 0
				global::UPM_IPS.JRPPCLMCFProyectoIPS.Clase result = root.Clase;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetClaseEnumeradorForMetaforaEnumeradorenumeradorDecFromLastLink(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumeradorHasEnumeradors root)
			{
				// Segment 0
				global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumerador result = root.ClaseEnumerador;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetClaseEnumeradorForMetaforaEnumeradorenumeradorDec(global::UPM_IPS.JRPPCLMCFProyectoIPS.Enumerador root)
			{
				// Segments 1 and 0
				global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumerador result = root.ClaseEnumerador;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			#endregion
	
			#region helper method to update compartments 
			/// <summary>
			/// Updates the compartments for the shapes associated to the given list of model elements
			/// </summary>
			/// <param name="elements">List of model elements</param>
			/// <param name="shapeType">The type of shape that needs updating</param>
			/// <param name="compartmentName">The name of the compartment to update</param>
			/// <param name="repaintOnly">If true, the method will only invalidate the shape for a repaint, without re-initializing the shape.</param>
			internal static void UpdateCompartments(global::System.Collections.IEnumerable elements, global::System.Type shapeType, string compartmentName, bool repaintOnly)
			{
				foreach (DslModeling::ModelElement element in elements)
				{
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
					foreach (DslDiagrams::PresentationElement pel in pels)
					{
						DslDiagrams::CompartmentShape compartmentShape = pel as DslDiagrams::CompartmentShape;
						if (compartmentShape != null && shapeType.IsAssignableFrom(compartmentShape.GetType()))
						{
							if (repaintOnly)
							{
								compartmentShape.Invalidate();
							}
							else
							{
								foreach(DslDiagrams::CompartmentMapping mapping in compartmentShape.GetCompartmentMappings())
								{
									if(mapping.CompartmentId==compartmentName)
									{
										mapping.InitializeCompartmentShape(compartmentShape);
										break;
									}
								}
							}
						}
					}
				}
			}
			#endregion
		}
		
		/// <summary>
		/// Rule to update compartments when an items is removed from the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumeradorHasEnumeradors), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemDeleteRule : DslModeling::DeleteRule
		{
			/// <summary>
			/// Called when an element is deleted
			/// </summary>
			/// <param name="e"></param>
			public override void ElementDeleted(DslModeling::ElementDeletedEventArgs e)
			{
				ElementDeleted(e, false);
			}
			
			internal static void ElementDeleted(DslModeling::ElementDeletedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetClaseForClaseMetaforaAtributoFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora), "Atributo", repaintOnly);
				}
				if(e.ModelElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetClaseForClaseMetaforaOpereacionFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora), "Opereacion", repaintOnly);
				}
				if(e.ModelElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetClaseEnriquecidaForClaseEnriquecidaShapeatributoDecFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape), "atributoDec", repaintOnly);
				}
				if(e.ModelElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetClaseEnriquecidaForClaseEnriquecidaShapeoperacionDecFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape), "operacionDec", repaintOnly);
				}
				if(e.ModelElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumeradorHasEnumeradors)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetClaseEnumeradorForMetaforaEnumeradorenumeradorDecFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumeradorHasEnumeradors)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaEnumerador), "enumeradorDec", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when the property on an item being displayed changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.Atributo), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.Operacion), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.Enumerador), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemChangeRule : DslModeling::ChangeRule 
		{
			/// <summary>
			/// Called when an element is changed
			/// </summary>
			/// <param name="e"></param>
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				ElementPropertyChanged(e, false);
			}
			
			internal static void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.Atributo && e.DomainProperty.Id == global::UPM_IPS.JRPPCLMCFProyectoIPS.Atributo.tipoDatoCalculadoDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseForClaseMetaforaAtributo((global::UPM_IPS.JRPPCLMCFProyectoIPS.Atributo)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora), "Atributo", repaintOnly);
				}
				if(e.ModelElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.Operacion && e.DomainProperty.Id == global::UPM_IPS.JRPPCLMCFProyectoIPS.Operacion.parametrosCalculadoDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseForClaseMetaforaOpereacion((global::UPM_IPS.JRPPCLMCFProyectoIPS.Operacion)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora), "Opereacion", repaintOnly);
				}
				if(e.ModelElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.Atributo && e.DomainProperty.Id == global::UPM_IPS.JRPPCLMCFProyectoIPS.Atributo.tipoDatoCalculadoDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseEnriquecidaForClaseEnriquecidaShapeatributoDec((global::UPM_IPS.JRPPCLMCFProyectoIPS.Atributo)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape), "atributoDec", repaintOnly);
				}
				if(e.ModelElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.Operacion && e.DomainProperty.Id == global::UPM_IPS.JRPPCLMCFProyectoIPS.Operacion.parametrosCalculadoDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseEnriquecidaForClaseEnriquecidaShapeoperacionDec((global::UPM_IPS.JRPPCLMCFProyectoIPS.Operacion)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape), "operacionDec", repaintOnly);
				}
				if(e.ModelElement is global::UPM_IPS.JRPPCLMCFProyectoIPS.Enumerador && e.DomainProperty.Id == global::UPM_IPS.JRPPCLMCFProyectoIPS.Enumerador.nombreDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseEnumeradorForMetaforaEnumeradorenumeradorDec((global::UPM_IPS.JRPPCLMCFProyectoIPS.Enumerador)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaEnumerador), "enumeradorDec", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when a roleplayer change happens
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumeradorHasEnumeradors), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerChangeRule : DslModeling::RolePlayerChangeRule 
		{
			/// <summary>
			/// Called when the roleplayer on a link changes.
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				RolePlayerChanged(e, false);
			}
			
			internal static void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetClaseForClaseMetaforaAtributoFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.Atributo)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora compartmentShape = pel as global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseForClaseMetaforaAtributoFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora), "Atributo", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseForClaseMetaforaAtributo((global::UPM_IPS.JRPPCLMCFProyectoIPS.Atributo)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora), "Atributo", repaintOnly);
					}
				}
				if(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetClaseForClaseMetaforaOpereacionFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.Operacion)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora compartmentShape = pel as global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[1].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseForClaseMetaforaOpereacionFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora), "Opereacion", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseForClaseMetaforaOpereacion((global::UPM_IPS.JRPPCLMCFProyectoIPS.Operacion)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora), "Opereacion", repaintOnly);
					}
				}
				if(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetClaseEnriquecidaForClaseEnriquecidaShapeatributoDecFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.Atributo)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape compartmentShape = pel as global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseEnriquecidaForClaseEnriquecidaShapeatributoDecFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape), "atributoDec", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseEnriquecidaForClaseEnriquecidaShapeatributoDec((global::UPM_IPS.JRPPCLMCFProyectoIPS.Atributo)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape), "atributoDec", repaintOnly);
					}
				}
				if(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetClaseEnriquecidaForClaseEnriquecidaShapeoperacionDecFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.Operacion)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape compartmentShape = pel as global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[1].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseEnriquecidaForClaseEnriquecidaShapeoperacionDecFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape), "operacionDec", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseEnriquecidaForClaseEnriquecidaShapeoperacionDec((global::UPM_IPS.JRPPCLMCFProyectoIPS.Operacion)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape), "operacionDec", repaintOnly);
					}
				}
				if(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumeradorHasEnumeradors).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetClaseEnumeradorForMetaforaEnumeradorenumeradorDecFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.Enumerador)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaEnumerador compartmentShape = pel as global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaEnumerador;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseEnumeradorForMetaforaEnumeradorenumeradorDecFromLastLink((global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumeradorHasEnumeradors)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaEnumerador), "enumeradorDec", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseEnumeradorForMetaforaEnumeradorenumeradorDec((global::UPM_IPS.JRPPCLMCFProyectoIPS.Enumerador)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaEnumerador), "enumeradorDec", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// Rule to update compartments when the order of items in the list changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumeradorHasEnumeradors), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerPositionChangeRule : DslModeling::RolePlayerPositionChangeRule 
		{
			/// <summary>
			/// Called when the order of a roleplayer in a relationship changes
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e)
			{
				RolePlayerPositionChanged(e, false);
			}
			
			internal static void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseForClaseMetaforaAtributo((global::UPM_IPS.JRPPCLMCFProyectoIPS.Atributo)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora), "Atributo", repaintOnly);
					}
				}
				if(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseForClaseMetaforaOpereacion((global::UPM_IPS.JRPPCLMCFProyectoIPS.Operacion)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseMetafora), "Opereacion", repaintOnly);
					}
				}
				if(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseEnriquecidaForClaseEnriquecidaShapeatributoDec((global::UPM_IPS.JRPPCLMCFProyectoIPS.Atributo)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape), "atributoDec", repaintOnly);
					}
				}
				if(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseEnriquecidaForClaseEnriquecidaShapeoperacionDec((global::UPM_IPS.JRPPCLMCFProyectoIPS.Operacion)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaShape), "operacionDec", repaintOnly);
					}
				}
				if(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumeradorHasEnumeradors).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetClaseEnumeradorForMetaforaEnumeradorenumeradorDec((global::UPM_IPS.JRPPCLMCFProyectoIPS.Enumerador)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaEnumerador), "enumeradorDec", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseComponeClases), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferenciaClase), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClasePadreHasClaseHija), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase.cardinalidadDCalculadaDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaClase_Clase.FindMetaforaClase_ClaseDecorator("cardinalidadDDec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase.cardinalidadOCalculadaDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaClase_Clase.FindMetaforaClase_ClaseDecorator("cardinalidadODec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase.nombreDDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaClase_Clase.FindMetaforaClase_ClaseDecorator("nombreDDec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase.nombreODomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaClase_Clase.FindMetaforaClase_ClaseDecorator("nombreODec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase.nombreRDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaClase_Clase.FindMetaforaClase_ClaseDecorator("nombreRDec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseComponeClases.cardinalidadDDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaRComposicion.FindMetaforaRComposicionDecorator("cardinalidadDDec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseComponeClases.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseComponeClases.cardinalidadODomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaRComposicion.FindMetaforaRComposicionDecorator("cardinalidadODec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseComponeClases.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseComponeClases.nombreDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaRComposicion.FindMetaforaRComposicionDecorator("nombreDec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseComponeClases.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferenciaClase.cardinalidadDDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaReferenciada.FindMetaforaReferenciadaDecorator("cardinalidadDDec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferenciaClase.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferenciaClase.cardinalidadODomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaReferenciada.FindMetaforaReferenciadaDecorator("cardinalidadODec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferenciaClase.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferenciaClase.nombreDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaReferenciada.FindMetaforaReferenciadaDecorator("nombreDec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferenciaClase.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.JRPPCLMCFProyectoIPS.ClasePadreHasClaseHija.tipoHerenciaDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JRPPCLMCFProyectoIPS.MetaforaHerencia.FindMetaforaHerenciaDecorator("tipoHerenciaDec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JRPPCLMCFProyectoIPS.ClasePadreHasClaseHija.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferencesClase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseComponeClases), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseReferenciaClase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClasePadreHasClaseHija), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDiagram diagram = linkShape.Diagram as global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
