//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM_IPS.JRPPCLMCFProyectoIPS
{
	/// <summary>
	/// DomainModel JRPPCLMCFProyectoIPSDomainModel
	/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPS
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel.DisplayName", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("0f2d462b-cca3-4635-a8d9-93fad5f37341")]
	public partial class JRPPCLMCFProyectoIPSDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// JRPPCLMCFProyectoIPSDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x0f2d462b, 0xcca3, 0x4635, 0xa8, 0xd9, 0x93, 0xfa, 0xd5, 0xf3, 0x73, 0x41);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public JRPPCLMCFProyectoIPSDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(TapizClassWeb),
				typeof(Clase),
				typeof(ClaseEnriquecida),
				typeof(Atributo),
				typeof(Operacion),
				typeof(AtributoIdentificador),
				typeof(EstiloClase),
				typeof(EstiloAtributo),
				typeof(EstiloOperacion),
				typeof(Parametro),
				typeof(ClaseEnumerador),
				typeof(Enumerador),
				typeof(TapizClassWebHasClase),
				typeof(ClaseHasAtributo),
				typeof(ClaseHasOperacion),
				typeof(ClaseHasAtributoIdentificador),
				typeof(OperacionHasParametro),
				typeof(ClaseEnriquecidaHasEstiloClase),
				typeof(ClaseEnriquecidaHasEstiloOperacion),
				typeof(ClaseEnriquecidaHasEstiloAtributo),
				typeof(ClaseReferencesClase),
				typeof(ClaseComponeClases),
				typeof(ClaseReferenciaClase),
				typeof(ClasePadreHasClaseHija),
				typeof(TapizClassWebHasClaseEnumeradors),
				typeof(ClaseEnumeradorHasEnumeradors),
				typeof(JRPPCLMCFProyectoIPSDiagram),
				typeof(MetaforaClase_Clase),
				typeof(MetaforaHerencia),
				typeof(MetaforaRComposicion),
				typeof(MetaforaReferenciada),
				typeof(EstiloClaseShape),
				typeof(EstiloOperacionShape),
				typeof(EstiloAtributoShape),
				typeof(MetaforaParametro),
				typeof(MetaforaAtributoIdentificador),
				typeof(ClaseMetafora),
				typeof(ClaseEnriquecidaShape),
				typeof(MetaforaEnumerador),
				typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.FixUpDiagram),
				typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.DecoratorPropertyChanged),
				typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ConnectorRolePlayerChanged),
				typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.CompartmentItemAddRule),
				typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.CompartmentItemDeleteRule),
				typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.CompartmentItemRolePlayerChangeRule),
				typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.CompartmentItemRolePlayerPositionChangeRule),
				typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.CompartmentItemChangeRule),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Clase), "nombre", Clase.nombreDomainPropertyId, typeof(Clase.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "nombre", Atributo.nombreDomainPropertyId, typeof(Atributo.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "tipoDato", Atributo.tipoDatoDomainPropertyId, typeof(Atributo.tipoDatoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "tipoDatoCalculado", Atributo.tipoDatoCalculadoDomainPropertyId, typeof(Atributo.tipoDatoCalculadoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "modAcceso", Atributo.modAccesoDomainPropertyId, typeof(Atributo.modAccesoPropertyHandler)),
				new DomainMemberInfo(typeof(Operacion), "nombre", Operacion.nombreDomainPropertyId, typeof(Operacion.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Operacion), "parametrosCalculado", Operacion.parametrosCalculadoDomainPropertyId, typeof(Operacion.parametrosCalculadoPropertyHandler)),
				new DomainMemberInfo(typeof(Operacion), "modAcceso", Operacion.modAccesoDomainPropertyId, typeof(Operacion.modAccesoPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoIdentificador), "nombre", AtributoIdentificador.nombreDomainPropertyId, typeof(AtributoIdentificador.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(AtributoIdentificador), "tipoDato", AtributoIdentificador.tipoDatoDomainPropertyId, typeof(AtributoIdentificador.tipoDatoPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoIdentificador), "tipoDatoCalculado", AtributoIdentificador.tipoDatoCalculadoDomainPropertyId, typeof(AtributoIdentificador.tipoDatoCalculadoPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoIdentificador), "modAcceso", AtributoIdentificador.modAccesoDomainPropertyId, typeof(AtributoIdentificador.modAccesoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "colorFondo", EstiloClase.colorFondoDomainPropertyId, typeof(EstiloClase.colorFondoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "colorLetra", EstiloClase.colorLetraDomainPropertyId, typeof(EstiloClase.colorLetraPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "tipoLetra", EstiloClase.tipoLetraDomainPropertyId, typeof(EstiloClase.tipoLetraPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "alineacion", EstiloClase.alineacionDomainPropertyId, typeof(EstiloClase.alineacionPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "textoNormal", EstiloClase.textoNormalDomainPropertyId, typeof(EstiloClase.textoNormalPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "checkBox", EstiloClase.checkBoxDomainPropertyId, typeof(EstiloClase.checkBoxPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "radioButton", EstiloClase.radioButtonDomainPropertyId, typeof(EstiloClase.radioButtonPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "nombre", EstiloClase.nombreDomainPropertyId, typeof(EstiloClase.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "colorFondoCalculado", EstiloClase.colorFondoCalculadoDomainPropertyId, typeof(EstiloClase.colorFondoCalculadoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "colorLetraCalculado", EstiloClase.colorLetraCalculadoDomainPropertyId, typeof(EstiloClase.colorLetraCalculadoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "tipoLetraCalculado", EstiloClase.tipoLetraCalculadoDomainPropertyId, typeof(EstiloClase.tipoLetraCalculadoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "alineacionCalculado", EstiloClase.alineacionCalculadoDomainPropertyId, typeof(EstiloClase.alineacionCalculadoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloAtributo), "tipoLetra", EstiloAtributo.tipoLetraDomainPropertyId, typeof(EstiloAtributo.tipoLetraPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloAtributo), "colorLetra", EstiloAtributo.colorLetraDomainPropertyId, typeof(EstiloAtributo.colorLetraPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloAtributo), "nombre", EstiloAtributo.nombreDomainPropertyId, typeof(EstiloAtributo.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(EstiloAtributo), "tipoLetraCalculado", EstiloAtributo.tipoLetraCalculadoDomainPropertyId, typeof(EstiloAtributo.tipoLetraCalculadoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloAtributo), "colorLetraCalculado", EstiloAtributo.colorLetraCalculadoDomainPropertyId, typeof(EstiloAtributo.colorLetraCalculadoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloOperacion), "tipoLetra", EstiloOperacion.tipoLetraDomainPropertyId, typeof(EstiloOperacion.tipoLetraPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloOperacion), "colorLetra", EstiloOperacion.colorLetraDomainPropertyId, typeof(EstiloOperacion.colorLetraPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloOperacion), "nombre", EstiloOperacion.nombreDomainPropertyId, typeof(EstiloOperacion.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(EstiloOperacion), "tipoLetraCalculado", EstiloOperacion.tipoLetraCalculadoDomainPropertyId, typeof(EstiloOperacion.tipoLetraCalculadoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloOperacion), "colorLetraCalculado", EstiloOperacion.colorLetraCalculadoDomainPropertyId, typeof(EstiloOperacion.colorLetraCalculadoPropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "tipoDato", Parametro.tipoDatoDomainPropertyId, typeof(Parametro.tipoDatoPropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "nombre", Parametro.nombreDomainPropertyId, typeof(Parametro.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "tipoParametro", Parametro.tipoParametroDomainPropertyId, typeof(Parametro.tipoParametroPropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "tipoParametroCalculado", Parametro.tipoParametroCalculadoDomainPropertyId, typeof(Parametro.tipoParametroCalculadoPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseEnumerador), "nombre", ClaseEnumerador.nombreDomainPropertyId, typeof(ClaseEnumerador.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Enumerador), "nombre", Enumerador.nombreDomainPropertyId, typeof(Enumerador.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(ClaseReferencesClase), "cardinalidadO", ClaseReferencesClase.cardinalidadODomainPropertyId, typeof(ClaseReferencesClase.cardinalidadOPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseReferencesClase), "cardinalidadD", ClaseReferencesClase.cardinalidadDDomainPropertyId, typeof(ClaseReferencesClase.cardinalidadDPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseReferencesClase), "nombreO", ClaseReferencesClase.nombreODomainPropertyId, typeof(ClaseReferencesClase.nombreOPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseReferencesClase), "nombreD", ClaseReferencesClase.nombreDDomainPropertyId, typeof(ClaseReferencesClase.nombreDPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseReferencesClase), "cardinalidadOCalculada", ClaseReferencesClase.cardinalidadOCalculadaDomainPropertyId, typeof(ClaseReferencesClase.cardinalidadOCalculadaPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseReferencesClase), "cardinalidadDCalculada", ClaseReferencesClase.cardinalidadDCalculadaDomainPropertyId, typeof(ClaseReferencesClase.cardinalidadDCalculadaPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseReferencesClase), "nombreR", ClaseReferencesClase.nombreRDomainPropertyId, typeof(ClaseReferencesClase.nombreRPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseComponeClases), "nombre", ClaseComponeClases.nombreDomainPropertyId, typeof(ClaseComponeClases.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(ClaseComponeClases), "cardinalidadO", ClaseComponeClases.cardinalidadODomainPropertyId, typeof(ClaseComponeClases.cardinalidadOPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseComponeClases), "cardinalidadD", ClaseComponeClases.cardinalidadDDomainPropertyId, typeof(ClaseComponeClases.cardinalidadDPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseReferenciaClase), "nombre", ClaseReferenciaClase.nombreDomainPropertyId, typeof(ClaseReferenciaClase.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(ClaseReferenciaClase), "cardinalidadO", ClaseReferenciaClase.cardinalidadODomainPropertyId, typeof(ClaseReferenciaClase.cardinalidadOPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseReferenciaClase), "cardinalidadD", ClaseReferenciaClase.cardinalidadDDomainPropertyId, typeof(ClaseReferenciaClase.cardinalidadDPropertyHandler)),
				new DomainMemberInfo(typeof(ClasePadreHasClaseHija), "tipoHerencia", ClasePadreHasClaseHija.tipoHerenciaDomainPropertyId, typeof(ClasePadreHasClaseHija.tipoHerenciaPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(TapizClassWebHasClase), "TapizClassWeb", TapizClassWebHasClase.TapizClassWebDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizClassWebHasClase), "Clase", TapizClassWebHasClase.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributo), "Clase", ClaseHasAtributo.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributo), "Atributo", ClaseHasAtributo.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasOperacion), "Clase", ClaseHasOperacion.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasOperacion), "Operacion", ClaseHasOperacion.OperacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributoIdentificador), "Clase", ClaseHasAtributoIdentificador.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributoIdentificador), "AtributoIdentificador", ClaseHasAtributoIdentificador.AtributoIdentificadorDomainRoleId),
				new DomainRolePlayerInfo(typeof(OperacionHasParametro), "Operacion", OperacionHasParametro.OperacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(OperacionHasParametro), "Parametro", OperacionHasParametro.ParametroDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasEstiloClase), "ClaseEnriquecida", ClaseEnriquecidaHasEstiloClase.ClaseEnriquecidaDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasEstiloClase), "EstiloClase", ClaseEnriquecidaHasEstiloClase.EstiloClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasEstiloOperacion), "ClaseEnriquecida", ClaseEnriquecidaHasEstiloOperacion.ClaseEnriquecidaDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasEstiloOperacion), "EstiloOperacion", ClaseEnriquecidaHasEstiloOperacion.EstiloOperacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasEstiloAtributo), "ClaseEnriquecida", ClaseEnriquecidaHasEstiloAtributo.ClaseEnriquecidaDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasEstiloAtributo), "EstiloAtributo", ClaseEnriquecidaHasEstiloAtributo.EstiloAtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferencesClase), "SourceClase", ClaseReferencesClase.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferencesClase), "TargetClase", ClaseReferencesClase.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseComponeClases), "SourceClase", ClaseComponeClases.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseComponeClases), "TargetClase", ClaseComponeClases.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferenciaClase), "SourceClase", ClaseReferenciaClase.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferenciaClase), "TargetClase", ClaseReferenciaClase.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClasePadreHasClaseHija), "SourceClase", ClasePadreHasClaseHija.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClasePadreHasClaseHija), "TargetClase", ClasePadreHasClaseHija.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizClassWebHasClaseEnumeradors), "TapizClassWeb", TapizClassWebHasClaseEnumeradors.TapizClassWebDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizClassWebHasClaseEnumeradors), "ClaseEnumerador", TapizClassWebHasClaseEnumeradors.ClaseEnumeradorDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnumeradorHasEnumeradors), "ClaseEnumerador", ClaseEnumeradorHasEnumeradors.ClaseEnumeradorDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnumeradorHasEnumeradors), "Enumerador", ClaseEnumeradorHasEnumeradors.EnumeradorDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(25);
				createElementMap.Add(typeof(TapizClassWeb), 0);
				createElementMap.Add(typeof(Clase), 1);
				createElementMap.Add(typeof(ClaseEnriquecida), 2);
				createElementMap.Add(typeof(Atributo), 3);
				createElementMap.Add(typeof(Operacion), 4);
				createElementMap.Add(typeof(AtributoIdentificador), 5);
				createElementMap.Add(typeof(EstiloClase), 6);
				createElementMap.Add(typeof(EstiloAtributo), 7);
				createElementMap.Add(typeof(EstiloOperacion), 8);
				createElementMap.Add(typeof(Parametro), 9);
				createElementMap.Add(typeof(ClaseEnumerador), 10);
				createElementMap.Add(typeof(Enumerador), 11);
				createElementMap.Add(typeof(JRPPCLMCFProyectoIPSDiagram), 12);
				createElementMap.Add(typeof(MetaforaClase_Clase), 13);
				createElementMap.Add(typeof(MetaforaHerencia), 14);
				createElementMap.Add(typeof(MetaforaRComposicion), 15);
				createElementMap.Add(typeof(MetaforaReferenciada), 16);
				createElementMap.Add(typeof(EstiloClaseShape), 17);
				createElementMap.Add(typeof(EstiloOperacionShape), 18);
				createElementMap.Add(typeof(EstiloAtributoShape), 19);
				createElementMap.Add(typeof(MetaforaParametro), 20);
				createElementMap.Add(typeof(MetaforaAtributoIdentificador), 21);
				createElementMap.Add(typeof(ClaseMetafora), 22);
				createElementMap.Add(typeof(ClaseEnriquecidaShape), 23);
				createElementMap.Add(typeof(MetaforaEnumerador), 24);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new TapizClassWeb(partition, propertyAssignments);
				case 1: return new Clase(partition, propertyAssignments);
				case 2: return new ClaseEnriquecida(partition, propertyAssignments);
				case 3: return new Atributo(partition, propertyAssignments);
				case 4: return new Operacion(partition, propertyAssignments);
				case 5: return new AtributoIdentificador(partition, propertyAssignments);
				case 6: return new EstiloClase(partition, propertyAssignments);
				case 7: return new EstiloAtributo(partition, propertyAssignments);
				case 8: return new EstiloOperacion(partition, propertyAssignments);
				case 9: return new Parametro(partition, propertyAssignments);
				case 10: return new ClaseEnumerador(partition, propertyAssignments);
				case 11: return new Enumerador(partition, propertyAssignments);
				case 12: return new JRPPCLMCFProyectoIPSDiagram(partition, propertyAssignments);
				case 13: return new MetaforaClase_Clase(partition, propertyAssignments);
				case 14: return new MetaforaHerencia(partition, propertyAssignments);
				case 15: return new MetaforaRComposicion(partition, propertyAssignments);
				case 16: return new MetaforaReferenciada(partition, propertyAssignments);
				case 17: return new EstiloClaseShape(partition, propertyAssignments);
				case 18: return new EstiloOperacionShape(partition, propertyAssignments);
				case 19: return new EstiloAtributoShape(partition, propertyAssignments);
				case 20: return new MetaforaParametro(partition, propertyAssignments);
				case 21: return new MetaforaAtributoIdentificador(partition, propertyAssignments);
				case 22: return new ClaseMetafora(partition, propertyAssignments);
				case 23: return new ClaseEnriquecidaShape(partition, propertyAssignments);
				case 24: return new MetaforaEnumerador(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(14);
				createElementLinkMap.Add(typeof(TapizClassWebHasClase), 0);
				createElementLinkMap.Add(typeof(ClaseHasAtributo), 1);
				createElementLinkMap.Add(typeof(ClaseHasOperacion), 2);
				createElementLinkMap.Add(typeof(ClaseHasAtributoIdentificador), 3);
				createElementLinkMap.Add(typeof(OperacionHasParametro), 4);
				createElementLinkMap.Add(typeof(ClaseEnriquecidaHasEstiloClase), 5);
				createElementLinkMap.Add(typeof(ClaseEnriquecidaHasEstiloOperacion), 6);
				createElementLinkMap.Add(typeof(ClaseEnriquecidaHasEstiloAtributo), 7);
				createElementLinkMap.Add(typeof(ClaseReferencesClase), 8);
				createElementLinkMap.Add(typeof(ClaseComponeClases), 9);
				createElementLinkMap.Add(typeof(ClaseReferenciaClase), 10);
				createElementLinkMap.Add(typeof(ClasePadreHasClaseHija), 11);
				createElementLinkMap.Add(typeof(TapizClassWebHasClaseEnumeradors), 12);
				createElementLinkMap.Add(typeof(ClaseEnumeradorHasEnumeradors), 13);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new TapizClassWebHasClase(partition, roleAssignments, propertyAssignments);
				case 1: return new ClaseHasAtributo(partition, roleAssignments, propertyAssignments);
				case 2: return new ClaseHasOperacion(partition, roleAssignments, propertyAssignments);
				case 3: return new ClaseHasAtributoIdentificador(partition, roleAssignments, propertyAssignments);
				case 4: return new OperacionHasParametro(partition, roleAssignments, propertyAssignments);
				case 5: return new ClaseEnriquecidaHasEstiloClase(partition, roleAssignments, propertyAssignments);
				case 6: return new ClaseEnriquecidaHasEstiloOperacion(partition, roleAssignments, propertyAssignments);
				case 7: return new ClaseEnriquecidaHasEstiloAtributo(partition, roleAssignments, propertyAssignments);
				case 8: return new ClaseReferencesClase(partition, roleAssignments, propertyAssignments);
				case 9: return new ClaseComponeClases(partition, roleAssignments, propertyAssignments);
				case 10: return new ClaseReferenciaClase(partition, roleAssignments, propertyAssignments);
				case 11: return new ClasePadreHasClaseHija(partition, roleAssignments, propertyAssignments);
				case 12: return new TapizClassWebHasClaseEnumeradors(partition, roleAssignments, propertyAssignments);
				case 13: return new ClaseEnumeradorHasEnumeradors(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return JRPPCLMCFProyectoIPSDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (JRPPCLMCFProyectoIPSDomainModel.resourceManager == null)
				{
					JRPPCLMCFProyectoIPSDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(JRPPCLMCFProyectoIPSDomainModel).Assembly);
				}
				return JRPPCLMCFProyectoIPSDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return JRPPCLMCFProyectoIPSDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return JRPPCLMCFProyectoIPSDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (JRPPCLMCFProyectoIPSDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new JRPPCLMCFProyectoIPSCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					JRPPCLMCFProyectoIPSDomainModel.copyClosure = copyFilter;
				}
				return JRPPCLMCFProyectoIPSDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (JRPPCLMCFProyectoIPSDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new JRPPCLMCFProyectoIPSDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					JRPPCLMCFProyectoIPSDomainModel.removeClosure = removeFilter;
				}
				return JRPPCLMCFProyectoIPSDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ConnectorRolePlayerChanged));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.CompartmentItemAddRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.CompartmentItemDeleteRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.CompartmentItemRolePlayerChangeRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.CompartmentItemChangeRule));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.ConnectorRolePlayerChanged));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.CompartmentItemAddRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.CompartmentItemDeleteRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.CompartmentItemRolePlayerChangeRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.CompartmentItemChangeRule));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class JRPPCLMCFProyectoIPSDeleteClosure : JRPPCLMCFProyectoIPSDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public JRPPCLMCFProyectoIPSDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class JRPPCLMCFProyectoIPSDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public JRPPCLMCFProyectoIPSDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM_IPS.JRPPCLMCFProyectoIPS.TapizClassWebHasClase.ClaseDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributo.AtributoDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasOperacion.OperacionDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseHasAtributoIdentificador.AtributoIdentificadorDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JRPPCLMCFProyectoIPS.OperacionHasParametro.ParametroDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaHasEstiloClase.EstiloClaseDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaHasEstiloOperacion.EstiloOperacionDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnriquecidaHasEstiloAtributo.EstiloAtributoDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JRPPCLMCFProyectoIPS.TapizClassWebHasClaseEnumeradors.ClaseEnumeradorDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JRPPCLMCFProyectoIPS.ClaseEnumeradorHasEnumeradors.EnumeradorDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class JRPPCLMCFProyectoIPSCopyClosure : JRPPCLMCFProyectoIPSCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public JRPPCLMCFProyectoIPSCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class JRPPCLMCFProyectoIPSCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public JRPPCLMCFProyectoIPSCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace UPM_IPS.JRPPCLMCFProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoDato
	/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoDato
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoDato
	{
		/// <summary>
		/// Boolean
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoDato.Boolean
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoDato/Boolean.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		Boolean = 0,
		/// <summary>
		/// Int
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoDato.Int
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoDato/Int.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		Int = 4,
		/// <summary>
		/// Char
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoDato.Char
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoDato/Char.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		Char = 1,
		/// <summary>
		/// String
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoDato.String
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoDato/String.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		String = 5,
		/// <summary>
		/// Float
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoDato.Float
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoDato/Float.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		Float = 3,
		/// <summary>
		/// Double
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoDato.Double
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoDato/Double.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		Double = 2,
		/// <summary>
		/// tipoHabitacion
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoDato.tipoHabitacion
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoDato/tipoHabitacion.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		tipoHabitacion = 6,
	}
}
namespace UPM_IPS.JRPPCLMCFProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoColor
	/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoColor
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoColor
	{
		/// <summary>
		/// rojo
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoColor.rojo
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoColor/rojo.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		rojo = 0,
		/// <summary>
		/// amarillo
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoColor.amarillo
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoColor/amarillo.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		amarillo = 1,
		/// <summary>
		/// verde
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoColor.verde
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoColor/verde.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		verde = 2,
		/// <summary>
		/// azul
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoColor.azul
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoColor/azul.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		azul = 3,
		/// <summary>
		/// negro
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoColor.negro
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoColor/negro.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		negro = 4,
	}
}
namespace UPM_IPS.JRPPCLMCFProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoLetra
	/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoLetra
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoLetra
	{
		/// <summary>
		/// TimesNewRoman
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoLetra.TimesNewRoman
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoLetra/TimesNewRoman.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		TimesNewRoman = 0,
		/// <summary>
		/// Calibri
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoLetra.Calibri
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoLetra/Calibri.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		Calibri = 1,
		/// <summary>
		/// Arial
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoLetra.Arial
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoLetra/Arial.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		Arial = 2,
	}
}
namespace UPM_IPS.JRPPCLMCFProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: Alineacion
	/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.Alineacion
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Alineacion
	{
		/// <summary>
		/// right
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.Alineacion.right
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.Alineacion/right.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		right = 0,
		/// <summary>
		/// center
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.Alineacion.center
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.Alineacion/center.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		center = 1,
		/// <summary>
		/// left
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.Alineacion.left
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.Alineacion/left.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		left = 2,
	}
}
namespace UPM_IPS.JRPPCLMCFProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoParametro
	/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoParametro
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoParametro
	{
		/// <summary>
		/// Entrada
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoParametro.Entrada
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoParametro/Entrada.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		Entrada = 0,
		/// <summary>
		/// Salida
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoParametro.Salida
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoParametro/Salida.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		Salida = 2,
		/// <summary>
		/// Entrada_Salida
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.TipoParametro.Entrada_Salida
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.TipoParametro/Entrada_Salida.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		Entrada_Salida = 1,
	}
}
namespace UPM_IPS.JRPPCLMCFProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: tipoCardinalidad
	/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.tipoCardinalidad
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum tipoCardinalidad
	{
		/// <summary>
		/// uno_uno
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.tipoCardinalidad.uno_uno
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.tipoCardinalidad/uno_uno.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		uno_uno = 4,
		/// <summary>
		/// uno_n
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.tipoCardinalidad.uno_n
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.tipoCardinalidad/uno_n.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		uno_n = 3,
		/// <summary>
		/// cero_n
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.tipoCardinalidad.cero_n
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.tipoCardinalidad/cero_n.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		cero_n = 0,
		/// <summary>
		/// n_n
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.tipoCardinalidad.n_n
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.tipoCardinalidad/n_n.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		n_n = 2,
		/// <summary>
		/// cero_uno
		/// Description for UPM_IPS.JRPPCLMCFProyectoIPS.tipoCardinalidad.cero_uno
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JRPPCLMCFProyectoIPS.tipoCardinalidad/cero_uno.Description", typeof(global::UPM_IPS.JRPPCLMCFProyectoIPS.JRPPCLMCFProyectoIPSDomainModel), "UPM_IPS.JRPPCLMCFProyectoIPS.GeneratedCode.DomainModelResx")]
		cero_uno = 1,
	}
}

