//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.JRPPCLMCFProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "JRPPCLMCFProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"JRPPCLMCFProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID JRPPCLMCFProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(JRPPCLMCFProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID JRPPCLMCFProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(JRPPCLMCFProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewJRPPCLMCFProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(JRPPCLMCFProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string JRPPCLMCFProyectoIPSPackageId = "67c649b8-57b5-4de9-81bd-8d7f08b3aa12";
		
		// Editor factory identifier
		public const string JRPPCLMCFProyectoIPSEditorFactoryId = "cb8ae405-df97-4a87-aa43-feea91a8e8fc";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string JRPPCLMCFProyectoIPSModelExplorerToolWindowId = "772ca560-d46a-445d-b337-ad45ba67f0e2";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.JRPPCLMCFProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string JRPPCLMCFProyectoIPSCommandSetId = "8e2325d3-7576-4929-b21f-5afad59cfcd7";
	}
}